services:
  db:
    image: postgres:18-alpine
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: spoleek
    ports:
      - "5432:5432"
    volumes:
      - spoleek_db_data:/var/lib/postgresql/data

  adminer:
    image: adminer:latest
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - db

volumes:
  spoleek_db_data:
